language: java

addons:
  hostname: short-hostname

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

install: true

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport coveralls || ./gradlew clean

notifications:
  irc: "irc.freenode.org#anchos"
