language: java

addons:
  hostname: short-hostname

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  irc: "irc.freenode.org#anchos"
