language: java

addons:
  hostname: short-hostname

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

install: true

script:
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport coveralls || ./gradlew clean

after_failure:
  - ./gradlew clean check --debug

notifications:
  irc: "irc.freenode.org#anchos"
